// Code generated by goadlc v3 - DO NOT EDIT.
package db

import (
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
)

type MetaAdlDecl struct {
	_MetaAdlDecl
}

type _MetaAdlDecl struct {
	Module_name adlast.ModuleName `json:"module_name"`
	Name        string            `json:"name"`
	Decl        adlast.Decl       `json:"decl"`
}

func MakeAll_MetaAdlDecl(
	module_name adlast.ModuleName,
	name string,
	decl adlast.Decl,
) MetaAdlDecl {
	return MetaAdlDecl{
		_MetaAdlDecl{
			Module_name: module_name,
			Name:        name,
			Decl:        decl,
		},
	}
}

func Make_MetaAdlDecl(
	module_name adlast.ModuleName,
	name string,
	decl adlast.Decl,
) MetaAdlDecl {
	ret := MetaAdlDecl{
		_MetaAdlDecl{
			Module_name: module_name,
			Name:        name,
			Decl:        decl,
		},
	}
	return ret
}

type MetaTable struct {
	_MetaTable
}

type _MetaTable struct {
	Name             string            `json:"name"`
	Description      string            `json:"description"`
	Decl_module_name adlast.ModuleName `json:"decl_module_name"`
	Decl_name        string            `json:"decl_name"`
}

func MakeAll_MetaTable(
	name string,
	description string,
	decl_module_name adlast.ModuleName,
	decl_name string,
) MetaTable {
	return MetaTable{
		_MetaTable{
			Name:             name,
			Description:      description,
			Decl_module_name: decl_module_name,
			Decl_name:        decl_name,
		},
	}
}

func Make_MetaTable(
	name string,
	description string,
	decl_module_name adlast.ModuleName,
	decl_name string,
) MetaTable {
	ret := MetaTable{
		_MetaTable{
			Name:             name,
			Description:      description,
			Decl_module_name: decl_module_name,
			Decl_name:        decl_name,
		},
	}
	return ret
}
