// Code generated by goadlc v3 - DO NOT EDIT.
package ui

import (
	"context"
	http2 "github.com/adl-lang/goadl_common/common/http"
	"github.com/adl-lang/goadl_protoapp/protoapp/db"
	"net/http"
)

type ApiRequests_Service interface {
	Healthy(ctx context.Context) (http2.Unit, error)
	Ping(ctx context.Context, req http2.Unit) (http2.Unit, error)
	Login(ctx context.Context, req LoginReq) (LoginResp, error)
	Refresh(ctx context.Context, req RefreshReq) (RefreshResp, error)
	Logout(ctx context.Context, req http2.Unit) (http2.Unit, error)
	NewMessage(ctx context.Context, req NewMessageReq) (db.MessageId, error)
	RecentMessages(ctx context.Context, req RecentMessagesReq) (Paginated[Message], error)
	WhoAmI(ctx context.Context) (UserProfile, error)
}

func Register_ApiRequests(
	mux *http.ServeMux,
	srv ApiRequests_Service,
) {
	reqs := Make_ApiRequests()
	http2.AdlGet(mux, reqs.Healthy, srv.Healthy)
	http2.AdlPost(mux, reqs.Ping, srv.Ping)
	http2.AdlPost(mux, reqs.Login, srv.Login)
	http2.AdlPost(mux, reqs.Refresh, srv.Refresh)
	http2.AdlPost(mux, reqs.Logout, srv.Logout)
	http2.AdlPost(mux, reqs.NewMessage, srv.NewMessage)
	http2.AdlPost(mux, reqs.RecentMessages, srv.RecentMessages)
	http2.AdlGet(mux, reqs.WhoAmI, srv.WhoAmI)
}
