// Code generated by goadlc v3 - DO NOT EDIT.
package strings

import ()

type EmailAddress = string

type Password = string

type StringANH = string

type StringMD = string

type StringML = string

type StringNE = string
