// Code generated by goadlc v3 - DO NOT EDIT.
package cap

import (
	"fmt"
	"github.com/adl-lang/goadl_common/common/capability"
	"github.com/adl-lang/goadl_common/common/http"
	strings2 "github.com/adl-lang/goadl_common/common/strings"
	"github.com/adl-lang/goadl_protoapp/protoapp/db"
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
	"time"
)

type AccessApiRequests struct {
	_AccessApiRequests
}

type _AccessApiRequests struct {
	NewMessage     capability.HttpPost[NewMessageReq, db.MessageId]           `json:"newMessage"`
	RecentMessages capability.HttpPost[RecentMessagesReq, Paginated[Message]] `json:"recentMessages"`
	WhoAmI         capability.HttpGet[UserProfile]                            `json:"whoAmI"`
}

func MakeAll_AccessApiRequests(
	newmessage capability.HttpPost[NewMessageReq, db.MessageId],
	recentmessages capability.HttpPost[RecentMessagesReq, Paginated[Message]],
	whoami capability.HttpGet[UserProfile],
) AccessApiRequests {
	return AccessApiRequests{
		_AccessApiRequests{
			NewMessage:     newmessage,
			RecentMessages: recentmessages,
			WhoAmI:         whoami,
		},
	}
}

func Make_AccessApiRequests() AccessApiRequests {
	ret := AccessApiRequests{
		_AccessApiRequests{
			NewMessage:     ((*AccessApiRequests)(nil)).Default_newMessage(),
			RecentMessages: ((*AccessApiRequests)(nil)).Default_recentMessages(),
			WhoAmI:         ((*AccessApiRequests)(nil)).Default_whoAmI(),
		},
	}
	return ret
}

func (*AccessApiRequests) Default_newMessage() capability.HttpPost[NewMessageReq, db.MessageId] {
	return capability.MakeAll_HttpPost[NewMessageReq, db.MessageId](
		"/messages/new",
		nil,
		adlast.Make_ATypeExpr[NewMessageReq](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.apis.cap",
					"NewMessageReq",
				),
			),
			[]adlast.TypeExpr{},
		)),
		adlast.Make_ATypeExpr[db.MessageId](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.db",
					"MessageId",
				),
			),
			[]adlast.TypeExpr{},
		)),
	)
}
func (*AccessApiRequests) Default_recentMessages() capability.HttpPost[RecentMessagesReq, Paginated[Message]] {
	return capability.MakeAll_HttpPost[RecentMessagesReq, Paginated[Message]](
		"/messages/recent",
		nil,
		adlast.Make_ATypeExpr[RecentMessagesReq](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.apis.cap",
					"RecentMessagesReq",
				),
			),
			[]adlast.TypeExpr{},
		)),
		adlast.Make_ATypeExpr[Paginated[Message]](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.apis.cap",
					"Paginated",
				),
			),
			[]adlast.TypeExpr{
				adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"protoapp.apis.cap",
							"Message",
						),
					),
					[]adlast.TypeExpr{},
				),
			},
		)),
	)
}
func (*AccessApiRequests) Default_whoAmI() capability.HttpGet[UserProfile] {
	return capability.MakeAll_HttpGet[UserProfile](
		"/whoami",
		nil,
		adlast.Make_ATypeExpr[UserProfile](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.apis.cap",
					"UserProfile",
				),
			),
			[]adlast.TypeExpr{},
		)),
	)
}

type AccessToken = strings2.StringNE

type ApiRequests struct {
	_ApiRequests
}

type _ApiRequests struct {
	Healthy         capability.HttpGet[http.Unit]                                         `json:"healthy"`
	Ping            capability.HttpPost[http.Unit, http.Unit]                             `json:"ping"`
	Login           capability.HttpPost[LoginReq, LoginResp]                              `json:"login"`
	Logout          capability.HttpPost[http.Unit, http.Unit]                             `json:"logout"`
	AccessTokenApi  capability.CapabilityApi[AccessToken, Capability, AccessApiRequests]  `json:"accessTokenApi"`
	RefreshTokenApi capability.CapabilityApi[RefreshToken, http.Unit, RefreshApiRequests] `json:"refreshTokenApi"`
}

func MakeAll_ApiRequests(
	healthy capability.HttpGet[http.Unit],
	ping capability.HttpPost[http.Unit, http.Unit],
	login capability.HttpPost[LoginReq, LoginResp],
	logout capability.HttpPost[http.Unit, http.Unit],
	accesstokenapi capability.CapabilityApi[AccessToken, Capability, AccessApiRequests],
	refreshtokenapi capability.CapabilityApi[RefreshToken, http.Unit, RefreshApiRequests],
) ApiRequests {
	return ApiRequests{
		_ApiRequests{
			Healthy:         healthy,
			Ping:            ping,
			Login:           login,
			Logout:          logout,
			AccessTokenApi:  accesstokenapi,
			RefreshTokenApi: refreshtokenapi,
		},
	}
}

func Make_ApiRequests() ApiRequests {
	ret := ApiRequests{
		_ApiRequests{
			Healthy:         ((*ApiRequests)(nil)).Default_healthy(),
			Ping:            ((*ApiRequests)(nil)).Default_ping(),
			Login:           ((*ApiRequests)(nil)).Default_login(),
			Logout:          ((*ApiRequests)(nil)).Default_logout(),
			AccessTokenApi:  ((*ApiRequests)(nil)).Default_accessTokenApi(),
			RefreshTokenApi: ((*ApiRequests)(nil)).Default_refreshTokenApi(),
		},
	}
	return ret
}

func (*ApiRequests) Default_healthy() capability.HttpGet[http.Unit] {
	return capability.MakeAll_HttpGet[http.Unit](
		"/",
		nil,
		adlast.Make_ATypeExpr[http.Unit](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"common.http",
					"Unit",
				),
			),
			[]adlast.TypeExpr{},
		)),
	)
}
func (*ApiRequests) Default_ping() capability.HttpPost[http.Unit, http.Unit] {
	return capability.MakeAll_HttpPost[http.Unit, http.Unit](
		"/ping",
		nil,
		adlast.Make_ATypeExpr[http.Unit](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"common.http",
					"Unit",
				),
			),
			[]adlast.TypeExpr{},
		)),
		adlast.Make_ATypeExpr[http.Unit](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"common.http",
					"Unit",
				),
			),
			[]adlast.TypeExpr{},
		)),
	)
}
func (*ApiRequests) Default_login() capability.HttpPost[LoginReq, LoginResp] {
	return capability.MakeAll_HttpPost[LoginReq, LoginResp](
		"/login",
		nil,
		adlast.Make_ATypeExpr[LoginReq](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.apis.cap",
					"LoginReq",
				),
			),
			[]adlast.TypeExpr{},
		)),
		adlast.Make_ATypeExpr[LoginResp](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.apis.cap",
					"LoginResp",
				),
			),
			[]adlast.TypeExpr{},
		)),
	)
}
func (*ApiRequests) Default_logout() capability.HttpPost[http.Unit, http.Unit] {
	return capability.MakeAll_HttpPost[http.Unit, http.Unit](
		"/logout",
		nil,
		adlast.Make_ATypeExpr[http.Unit](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"common.http",
					"Unit",
				),
			),
			[]adlast.TypeExpr{},
		)),
		adlast.Make_ATypeExpr[http.Unit](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"common.http",
					"Unit",
				),
			),
			[]adlast.TypeExpr{},
		)),
	)
}
func (*ApiRequests) Default_accessTokenApi() capability.CapabilityApi[AccessToken, Capability, AccessApiRequests] {
	return capability.MakeAll_CapabilityApi[AccessToken, Capability, AccessApiRequests](
		capability.MakeAll_CapabilityDefn[AccessToken, Capability](
			adlast.Make_ATypeExpr[AccessToken](adlast.MakeAll_TypeExpr(
				adlast.Make_TypeRef_reference(
					adlast.MakeAll_ScopedName(
						"protoapp.apis.cap",
						"AccessToken",
					),
				),
				[]adlast.TypeExpr{},
			)),
			adlast.Make_ATypeExpr[Capability](adlast.MakeAll_TypeExpr(
				adlast.Make_TypeRef_reference(
					adlast.MakeAll_ScopedName(
						"protoapp.apis.cap",
						"Capability",
					),
				),
				[]adlast.TypeExpr{},
			)),
		),
		"",
		MakeAll_AccessApiRequests(
			capability.MakeAll_HttpPost[NewMessageReq, db.MessageId](
				"/messages/new",
				nil,
				adlast.Make_ATypeExpr[NewMessageReq](adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"protoapp.apis.cap",
							"NewMessageReq",
						),
					),
					[]adlast.TypeExpr{},
				)),
				adlast.Make_ATypeExpr[db.MessageId](adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"protoapp.db",
							"MessageId",
						),
					),
					[]adlast.TypeExpr{},
				)),
			),
			capability.MakeAll_HttpPost[RecentMessagesReq, Paginated[Message]](
				"/messages/recent",
				nil,
				adlast.Make_ATypeExpr[RecentMessagesReq](adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"protoapp.apis.cap",
							"RecentMessagesReq",
						),
					),
					[]adlast.TypeExpr{},
				)),
				adlast.Make_ATypeExpr[Paginated[Message]](adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"protoapp.apis.cap",
							"Paginated",
						),
					),
					[]adlast.TypeExpr{
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"protoapp.apis.cap",
									"Message",
								),
							),
							[]adlast.TypeExpr{},
						),
					},
				)),
			),
			capability.MakeAll_HttpGet[UserProfile](
				"/whoami",
				nil,
				adlast.Make_ATypeExpr[UserProfile](adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"protoapp.apis.cap",
							"UserProfile",
						),
					),
					[]adlast.TypeExpr{},
				)),
			),
		),
	)
}
func (*ApiRequests) Default_refreshTokenApi() capability.CapabilityApi[RefreshToken, http.Unit, RefreshApiRequests] {
	return capability.MakeAll_CapabilityApi[RefreshToken, http.Unit, RefreshApiRequests](
		capability.MakeAll_CapabilityDefn[RefreshToken, http.Unit](
			adlast.Make_ATypeExpr[RefreshToken](adlast.MakeAll_TypeExpr(
				adlast.Make_TypeRef_reference(
					adlast.MakeAll_ScopedName(
						"protoapp.apis.cap",
						"RefreshToken",
					),
				),
				[]adlast.TypeExpr{},
			)),
			adlast.Make_ATypeExpr[http.Unit](adlast.MakeAll_TypeExpr(
				adlast.Make_TypeRef_reference(
					adlast.MakeAll_ScopedName(
						"common.http",
						"Unit",
					),
				),
				[]adlast.TypeExpr{},
			)),
		),
		"",
		MakeAll_RefreshApiRequests(
			capability.MakeAll_HttpPost[RefreshReq, RefreshResp](
				"/refresh",
				nil,
				adlast.Make_ATypeExpr[RefreshReq](adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"protoapp.apis.cap",
							"RefreshReq",
						),
					),
					[]adlast.TypeExpr{},
				)),
				adlast.Make_ATypeExpr[RefreshResp](adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"protoapp.apis.cap",
							"RefreshResp",
						),
					),
					[]adlast.TypeExpr{},
				)),
			),
		),
	)
}

type Capability struct {
	_Capability
}

type _Capability struct {
	User_id string   `json:"user_id"`
	Roles   []string `json:"roles"`
}

func MakeAll_Capability(
	user_id string,
	roles []string,
) Capability {
	return Capability{
		_Capability{
			User_id: user_id,
			Roles:   roles,
		},
	}
}

func Make_Capability(
	user_id string,
	roles []string,
) Capability {
	ret := Capability{
		_Capability{
			User_id: user_id,
			Roles:   roles,
		},
	}
	return ret
}

type LoginReq struct {
	_LoginReq
}

type _LoginReq struct {
	Email    strings2.StringNE `json:"email"`
	Password strings2.Password `json:"password"`
}

func MakeAll_LoginReq(
	email strings2.StringNE,
	password strings2.Password,
) LoginReq {
	return LoginReq{
		_LoginReq{
			Email:    email,
			Password: password,
		},
	}
}

func Make_LoginReq(
	email strings2.StringNE,
	password strings2.Password,
) LoginReq {
	ret := LoginReq{
		_LoginReq{
			Email:    email,
			Password: password,
		},
	}
	return ret
}

type LoginResp struct {
	Branch LoginRespBranch
}

type LoginRespBranch interface {
	isLoginRespBranch()
}

func (*LoginResp) MakeNewBranch(key string) (any, error) {
	switch key {
	case "tokens":
		return &_LoginResp_Tokens{}, nil
	case "invalid_credentials":
		return &_LoginResp_Invalid_credentials{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _LoginResp_Tokens struct {
	V LoginTokens `branch:"tokens"`
}
type _LoginResp_Invalid_credentials struct {
	V struct{} `branch:"invalid_credentials"`
}

func (_LoginResp_Tokens) isLoginRespBranch()              {}
func (_LoginResp_Invalid_credentials) isLoginRespBranch() {}

func Make_LoginResp_tokens(v LoginTokens) LoginResp {
	return LoginResp{
		_LoginResp_Tokens{v},
	}
}

func Make_LoginResp_invalid_credentials() LoginResp {
	return LoginResp{
		_LoginResp_Invalid_credentials{struct{}{}},
	}
}

func (un LoginResp) Cast_tokens() (LoginTokens, bool) {
	br, ok := un.Branch.(_LoginResp_Tokens)
	return br.V, ok
}

func (un LoginResp) Cast_invalid_credentials() (struct{}, bool) {
	br, ok := un.Branch.(_LoginResp_Invalid_credentials)
	return br.V, ok
}

func Handle_LoginResp[T any](
	_in LoginResp,
	tokens func(tokens LoginTokens) T,
	invalid_credentials func(invalid_credentials struct{}) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _LoginResp_Tokens:
		if tokens != nil {
			return tokens(_b.V)
		}
	case _LoginResp_Invalid_credentials:
		if invalid_credentials != nil {
			return invalid_credentials(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : LoginResp")
}

func HandleWithErr_LoginResp[T any](
	_in LoginResp,
	tokens func(tokens LoginTokens) (T, error),
	invalid_credentials func(invalid_credentials struct{}) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _LoginResp_Tokens:
		if tokens != nil {
			return tokens(_b.V)
		}
	case _LoginResp_Invalid_credentials:
		if invalid_credentials != nil {
			return invalid_credentials(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : LoginResp")
}

type LoginTokens struct {
	_LoginTokens
}

type _LoginTokens struct {
	Access_jwt  strings2.StringNE `json:"access_jwt"`
	Refresh_jwt strings2.StringNE `json:"refresh_jwt"`
}

func MakeAll_LoginTokens(
	access_jwt strings2.StringNE,
	refresh_jwt strings2.StringNE,
) LoginTokens {
	return LoginTokens{
		_LoginTokens{
			Access_jwt:  access_jwt,
			Refresh_jwt: refresh_jwt,
		},
	}
}

func Make_LoginTokens(
	access_jwt strings2.StringNE,
	refresh_jwt strings2.StringNE,
) LoginTokens {
	ret := LoginTokens{
		_LoginTokens{
			Access_jwt:  access_jwt,
			Refresh_jwt: refresh_jwt,
		},
	}
	return ret
}

type Message struct {
	_Message
}

type _Message struct {
	Id            db.MessageId      `json:"id"`
	Posted_at     time.Time         `json:"posted_at"`
	User_fullname string            `json:"user_fullname"`
	Message       strings2.StringML `json:"message"`
}

func MakeAll_Message(
	id db.MessageId,
	posted_at time.Time,
	user_fullname string,
	message strings2.StringML,
) Message {
	return Message{
		_Message{
			Id:            id,
			Posted_at:     posted_at,
			User_fullname: user_fullname,
			Message:       message,
		},
	}
}

func Make_Message(
	id db.MessageId,
	posted_at time.Time,
	user_fullname string,
	message strings2.StringML,
) Message {
	ret := Message{
		_Message{
			Id:            id,
			Posted_at:     posted_at,
			User_fullname: user_fullname,
			Message:       message,
		},
	}
	return ret
}

type NewMessageReq struct {
	_NewMessageReq
}

type _NewMessageReq struct {
	Message strings2.StringML `json:"message"`
}

func MakeAll_NewMessageReq(
	message strings2.StringML,
) NewMessageReq {
	return NewMessageReq{
		_NewMessageReq{
			Message: message,
		},
	}
}

func Make_NewMessageReq(
	message strings2.StringML,
) NewMessageReq {
	ret := NewMessageReq{
		_NewMessageReq{
			Message: message,
		},
	}
	return ret
}

type Paginated[T any] struct {
	_Paginated[T]
}

type _Paginated[T any] struct {
	Items          []T    `json:"items"`
	Current_offset uint32 `json:"current_offset"`
	Total_count    uint32 `json:"total_count"`
}

func MakeAll_Paginated[T any](
	items []T,
	current_offset uint32,
	total_count uint32,
) Paginated[T] {
	return Paginated[T]{
		_Paginated[T]{
			Items:          items,
			Current_offset: current_offset,
			Total_count:    total_count,
		},
	}
}

func Make_Paginated[T any](
	items []T,
	current_offset uint32,
	total_count uint32,
) Paginated[T] {
	ret := Paginated[T]{
		_Paginated[T]{
			Items:          items,
			Current_offset: current_offset,
			Total_count:    total_count,
		},
	}
	return ret
}

type RecentMessagesReq struct {
	_RecentMessagesReq
}

type _RecentMessagesReq struct {
	Offset uint32 `json:"offset"`
	Limit  uint32 `json:"limit"`
}

func MakeAll_RecentMessagesReq(
	offset uint32,
	limit uint32,
) RecentMessagesReq {
	return RecentMessagesReq{
		_RecentMessagesReq{
			Offset: offset,
			Limit:  limit,
		},
	}
}

func Make_RecentMessagesReq() RecentMessagesReq {
	ret := RecentMessagesReq{
		_RecentMessagesReq{
			Offset: ((*RecentMessagesReq)(nil)).Default_offset(),
			Limit:  ((*RecentMessagesReq)(nil)).Default_limit(),
		},
	}
	return ret
}

func (*RecentMessagesReq) Default_offset() uint32 {
	return 0
}
func (*RecentMessagesReq) Default_limit() uint32 {
	return 20
}

type RefreshApiRequests struct {
	_RefreshApiRequests
}

type _RefreshApiRequests struct {
	Refresh capability.HttpPost[RefreshReq, RefreshResp] `json:"refresh"`
}

func MakeAll_RefreshApiRequests(
	refresh capability.HttpPost[RefreshReq, RefreshResp],
) RefreshApiRequests {
	return RefreshApiRequests{
		_RefreshApiRequests{
			Refresh: refresh,
		},
	}
}

func Make_RefreshApiRequests() RefreshApiRequests {
	ret := RefreshApiRequests{
		_RefreshApiRequests{
			Refresh: ((*RefreshApiRequests)(nil)).Default_refresh(),
		},
	}
	return ret
}

func (*RefreshApiRequests) Default_refresh() capability.HttpPost[RefreshReq, RefreshResp] {
	return capability.MakeAll_HttpPost[RefreshReq, RefreshResp](
		"/refresh",
		nil,
		adlast.Make_ATypeExpr[RefreshReq](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.apis.cap",
					"RefreshReq",
				),
			),
			[]adlast.TypeExpr{},
		)),
		adlast.Make_ATypeExpr[RefreshResp](adlast.MakeAll_TypeExpr(
			adlast.Make_TypeRef_reference(
				adlast.MakeAll_ScopedName(
					"protoapp.apis.cap",
					"RefreshResp",
				),
			),
			[]adlast.TypeExpr{},
		)),
	)
}

type RefreshReq struct {
	_RefreshReq
}

type _RefreshReq struct {
	Refresh_token *strings2.StringNE `json:"refresh_token"`
}

func MakeAll_RefreshReq(
	refresh_token *strings2.StringNE,
) RefreshReq {
	return RefreshReq{
		_RefreshReq{
			Refresh_token: refresh_token,
		},
	}
}

func Make_RefreshReq() RefreshReq {
	ret := RefreshReq{
		_RefreshReq{
			Refresh_token: ((*RefreshReq)(nil)).Default_refresh_token(),
		},
	}
	return ret
}

func (*RefreshReq) Default_refresh_token() *strings2.StringNE {
	return nil
}

type RefreshResp struct {
	Branch RefreshRespBranch
}

type RefreshRespBranch interface {
	isRefreshRespBranch()
}

func (*RefreshResp) MakeNewBranch(key string) (any, error) {
	switch key {
	case "access_token":
		return &_RefreshResp_Access_token{}, nil
	case "invalid_refresh_token":
		return &_RefreshResp_Invalid_refresh_token{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _RefreshResp_Access_token struct {
	V strings2.StringNE `branch:"access_token"`
}
type _RefreshResp_Invalid_refresh_token struct {
	V struct{} `branch:"invalid_refresh_token"`
}

func (_RefreshResp_Access_token) isRefreshRespBranch()          {}
func (_RefreshResp_Invalid_refresh_token) isRefreshRespBranch() {}

func Make_RefreshResp_access_token(v strings2.StringNE) RefreshResp {
	return RefreshResp{
		_RefreshResp_Access_token{v},
	}
}

func Make_RefreshResp_invalid_refresh_token() RefreshResp {
	return RefreshResp{
		_RefreshResp_Invalid_refresh_token{struct{}{}},
	}
}

func (un RefreshResp) Cast_access_token() (strings2.StringNE, bool) {
	br, ok := un.Branch.(_RefreshResp_Access_token)
	return br.V, ok
}

func (un RefreshResp) Cast_invalid_refresh_token() (struct{}, bool) {
	br, ok := un.Branch.(_RefreshResp_Invalid_refresh_token)
	return br.V, ok
}

func Handle_RefreshResp[T any](
	_in RefreshResp,
	access_token func(access_token strings2.StringNE) T,
	invalid_refresh_token func(invalid_refresh_token struct{}) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _RefreshResp_Access_token:
		if access_token != nil {
			return access_token(_b.V)
		}
	case _RefreshResp_Invalid_refresh_token:
		if invalid_refresh_token != nil {
			return invalid_refresh_token(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RefreshResp")
}

func HandleWithErr_RefreshResp[T any](
	_in RefreshResp,
	access_token func(access_token strings2.StringNE) (T, error),
	invalid_refresh_token func(invalid_refresh_token struct{}) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _RefreshResp_Access_token:
		if access_token != nil {
			return access_token(_b.V)
		}
	case _RefreshResp_Invalid_refresh_token:
		if invalid_refresh_token != nil {
			return invalid_refresh_token(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RefreshResp")
}

type RefreshToken = strings2.StringNE

type UserProfile struct {
	_UserProfile
}

type _UserProfile struct {
	Id       db.AppUserId `json:"id"`
	Fullname string       `json:"fullname"`
	Email    string       `json:"email"`
	Is_admin bool         `json:"is_admin"`
}

func MakeAll_UserProfile(
	id db.AppUserId,
	fullname string,
	email string,
	is_admin bool,
) UserProfile {
	return UserProfile{
		_UserProfile{
			Id:       id,
			Fullname: fullname,
			Email:    email,
			Is_admin: is_admin,
		},
	}
}

func Make_UserProfile(
	id db.AppUserId,
	fullname string,
	email string,
	is_admin bool,
) UserProfile {
	ret := UserProfile{
		_UserProfile{
			Id:       id,
			Fullname: fullname,
			Email:    email,
			Is_admin: is_admin,
		},
	}
	return ret
}
