# always on main; on PRs only if deno code has changed
name: Deno CI
on:
  push:
    branches: [master]
  pull_request:
    paths:
      - "deno/**"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno using local-setup script
        run: |
          source deno/local-setup.sh
          deno --version

      - name: Check formatting
        working-directory: ./deno
        run: deno fmt --check

      - name: Run linter
        working-directory: ./deno
        run: deno lint
